
(let ([v0 (vector (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1) (vector 1) (vector 1) (vector 1)
                  (vector 1) (vector 1))])
  (+ (+ (+ (+ (+ (+ (vector-ref (vector-ref v0 0) 0)
                    (vector-ref (vector-ref v0 1) 0))
                 (+ (vector-ref (vector-ref v0 2) 0)
                    (vector-ref (vector-ref v0 3) 0)))
              (+ (+ (vector-ref (vector-ref v0 4) 0)
                    (vector-ref (vector-ref v0 5) 0))
                 (+ (vector-ref (vector-ref v0 6) 0)
                    (vector-ref (vector-ref v0 7) 0))))
           (+ (+ (+ (vector-ref (vector-ref v0 8) 0)
                    (vector-ref (vector-ref v0 9) 0))
                 (+ (vector-ref (vector-ref v0 10) 0)
                    (vector-ref (vector-ref v0 11) 0)))
              (+ (+ (vector-ref (vector-ref v0 12) 0)
                    (vector-ref (vector-ref v0 13) 0))
                 (+ (vector-ref (vector-ref v0 14) 0)
                    (vector-ref (vector-ref v0 15) 0)))))
        (+ (+ (+ (+ (vector-ref (vector-ref v0 16) 0)
                    (vector-ref (vector-ref v0 17) 0))
                 (+ (vector-ref (vector-ref v0 18) 0)
                    (vector-ref (vector-ref v0 19) 0)))
              (+ (+ (vector-ref (vector-ref v0 20) 0)
                    (vector-ref (vector-ref v0 21) 0))
                 (+ (vector-ref (vector-ref v0 22) 0)
                    (vector-ref (vector-ref v0 23) 0))))
           (+ (+ (+ (vector-ref (vector-ref v0 24) 0)
                    (vector-ref (vector-ref v0 25) 0))
                 (+ (vector-ref (vector-ref v0 26) 0)
                    (vector-ref (vector-ref v0 27) 0)))
              (+ (+ (vector-ref (vector-ref v0 28) 0)
                    (vector-ref (vector-ref v0 29) 0))
                 (+ (vector-ref (vector-ref v0 30) 0)
                    (vector-ref (vector-ref v0 31) 0))))))
     (+ (+ (+ (+ (vector-ref (vector-ref v0 32) 0)
                 (vector-ref (vector-ref v0 33) 0))
              (+ (vector-ref (vector-ref v0 34) 0)
                 (vector-ref (vector-ref v0 35) 0)))
           (+ (+ (vector-ref (vector-ref v0 36) 0)
                 (vector-ref (vector-ref v0 37) 0))
              (+ (vector-ref (vector-ref v0 38) 0)
                 (vector-ref (vector-ref v0 39) 0))))
        (+ (vector-ref (vector-ref v0 40) 0)
           (vector-ref (vector-ref v0 41) 0)))))

